# Generated by Django 5.2.4 on 2025-07-22 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Civil', 'Civil'), ('Criminal', 'Criminal'), ('Family', 'Family'), ('Divorce', 'Divorce'), ('Corporate', 'Corporate'), ('Intellectual Property', 'Intellectual Property'), ('Employment', 'Employment'), ('Tax', 'Tax'), ('Real Estate', 'Real Estate'), ('Bankruptcy', 'Bankruptcy'), ('Other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Pending', 'Pending'), ('Resolved', 'Resolved'), ('In Progress', 'In Progress')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
